name: Push check

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test