name: Push check

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Notes
          path: app/build/outputs/apk/debug/app-debug.apk

#      - name: Upload to Firebase
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ secrets.FIREBASE_APP_ID }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: Gita
#          file: app/build/outputs/apk/debug/app-debug.apk
#          releaseNotes: New version of the app